### ISSUE TITLE
Object.groupBy() undefined on firefox

### ISSUE THREAD

**Issue by Benoit485** [pantaflex44/Tiquettes#1]
Bonjour

Object.groupBy() est indéfini sur Firefox et du coup ça ne fonctionne pas

Il faudrait charger manuellement la fonction dans le cas ou elle n'existe pas

En tous cas merci ça m'a l'air prometteur, parce que le logiciel de schneider il est trop complexe et pas assez personnalisable

Peut être rajouté le schéma serait un +

**Comment by pantaflex44** [comment]
Petite preview, mais chuuutttt 😉


![IMG-20241208-WA0005.jpg](https://github.com/user-attachments/assets/bb2b34bf-534b-43a8-9b65-4ded8e3790d5)

**Comment by Benoit485** [comment]
c'est top :)
