### ISSUE TITLE
Taille de îcone

### ISSUE THREAD

**Issue by fmdl** [pantaflex44/Tiquettes#2]
Bonjour serais-t-il possible d'avoir une option pour réduire la taille des icônes, afin de mettre plus de texte.

**Comment by pantaflex44** [comment]
Bonsoir,

La taille des icônes dépend directement des thèmes proposés.
Donc je peux ajouter, dans la prochaine version, 1 ou 2 thèmes permettant une quantité de texte plus importante :-)

**Comment by pantaflex44** [comment]
Toute fraiche, la version 2.0.0 est sortie! J'ai intégré 2 nouveaux thèmes ayant une zone plus grande pour le descriptif textuel :-)
J'espère que celà vous conviendra!
