### ISSUE TITLE
[Schéma] élements en triple dans le schéma

### ISSUE THREAD

**Issue by fmdl** [pantaflex44/Tiquettes#5]
Bonjour,

Lors de l'éditions du schéma il y a ces éléments qui sont en triples:

![image](https://github.com/user-attachments/assets/f01ca571-1af1-4a46-9a4b-a7115d50537e)
[Tiquettes - 12 allée fleurie - v7.json](https://github.com/user-attachments/files/18250790/Tiquettes.-.12.allee.fleurie.-.v7.json)

**Comment by pantaflex44** [comment]
Mince, pourriez m'envoyer votre projet exporté que je regarde le comportement svp

**Comment by pantaflex44** [comment]
Le problème est corrigé. Fermez votre projet, rafraichissez la page de l'application et importez le de nouveau.

Le problème provient des identifiants des modules qui se retrouvent parfois en doublon. Le générateur de schéma n'arrivait pas à faire de différences.
C'est désormais corrigé. Les identifiants en doublons sont désormais automatiquement renommés, ce qui permet de générer cette fois, un schéma correct :-)

N'hésitez pas travailler vos identifiants. 

C'est une correction d'urgence, mais à l'avenir je ferai en sorte que vous ne puissiez pas créer un module avec un identifiant existant.

En espèrant avoir répondu à votre problème!

**Comment by fmdl** [comment]
Oui, merci, il serait pas mal d'avoir un bouton pour re-séquencer les disjoncteurs.

**Comment by fmdl** [comment]
Pour éviter se problème, il faudrait que vous génériez un identifiant unique par disjoncteur (uuid) pour qu'il soit invariant.

**Comment by pantaflex44** [comment]
> Oui, merci, il serait pas mal d'avoir un bouton pour re-séquencer les disjoncteurs.

Normalement ça le fait automatiquement mais effectivement ça fonctionne très mal (je l'avais remarqué une fois)



> Pour éviter se problème, il faudrait que vous génériez un identifiant unique par disjoncteur (uuid) pour qu'il soit invariant.

Effectivement, c'est une exelente idée


Je me permets de fermer l'issue, si tout est ok pour vous.

**Comment by pantaflex44** [comment]
> Oui, merci, il serait pas mal d'avoir un bouton pour re-séquencer les disjoncteurs.

Vœux du 1er de l'an exhaussé :-)

Lors de l'édition d'un module, il est possible de retrouver le dernier identifiant disponible dépendamment de la fonction définie de celui-ci.

![NextID](https://github.com/pantaflex44/Tiquettes/blob/main/docs/_next_id.png?raw=true)

Un nouveau bouton est apparu dans les barre à outils des onglets "Editeur" et "Schéma", permettant le ré assignement automatique des modules définis, toujours dépendamment de la fonction des modules.

![AutoID](https://github.com/pantaflex44/Tiquettes/blob/main/docs/_auto_id.png?raw=true)

Pour finir, si vous définissez un ID déjà utilisé lors de l'édition d'un module, alors l'application va tout simplement le remplacer par sa prochaine itération lorsque vous enregistrerez les modifications.

En espérant que cela vous convienne ;-)
En tout cas, merci pour cette excellente idée!
