### ISSUE TITLE
Fausse Erreur : indique qu'il faut un type A alors qu'il y a un type A

### ISSUE THREAD

**Issue by fmdl** [pantaflex44/Tiquettes#6]
![image](https://github.com/user-attachments/assets/51f63939-3893-4eab-a891-f551f00743ed)

[Tiquettes - 12 allée fleurie - v9.json](https://github.com/user-attachments/files/18251454/Tiquettes.-.12.allee.fleurie.-.v9.json)

**Comment by pantaflex44** [comment]
Oui j'ai regardé votre schéma. Vous avez défini un disjoncteur différentiel et non un interrupteur différentiel. 

Transformez le DD en ID et l'erreur disparaitra.
